# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-02 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0213_auto_20210129_1320'),
        ('disturbance', '0214_apiaryreferral_assigned_officer'),
    ]

    operations = [
    ]
