# Generated by Django 3.2.25 on 2025-10-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0294_auto_20251013_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='prefill_requested',
            field=models.BooleanField(default=False),
        ),
    ]
