# Generated by Django 3.2.25 on 2025-10-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0295_proposal_prefill_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='prefill_requested',
        ),
    ]
