# Generated by Django 3.2.25 on 2025-10-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0296_remove_proposal_prefill_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='exempt_from_radius_restriction',
            field=models.BooleanField(default=False),
        ),
    ]
