# Generated by Django 5.2.7 on 2025-10-16 03:53

import disturbance.components.ap_payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0297_apiarysite_exempt_from_radius_restriction'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymatrix',
            name='schema',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='annualrentalfee',
            name='lines',
            field=models.JSONField(default=disturbance.components.ap_payments.models.get_default_lines),
        ),
        migrations.AlterField(
            model_name='apiaryapprovergroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ApiaryApproverGroupMember', through_fields=('apiaryapprovergroup', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiaryassessorgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ApiaryAssessorGroupMember', through_fields=('apiaryassessorgroup', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiarychecklistanswer',
            name='answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiaryorganisationaccessgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ApiaryOrganisationAccessGroupMember', through_fields=('apiaryorganisationaccessgroup', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiaryreferralgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ApiaryReferralGroupMember', through_fields=('apiaryreferralgroup', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiarysiteonapproval',
            name='dra_permit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiarysiteonapproval',
            name='issuance_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiarysiteonproposal',
            name='issuance_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='extracted_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='surrender_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='suspension_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlistquestion',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='organisationaccessgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.OrganisationAccessGroupMember', through_fields=('organisationaccessgroup', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='assessor_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='comment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposed_issuance_approval',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='schema',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='proposalapprovergroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ProposalApproverGroupMember', through_fields=('proposalapprovergroup', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalassessorgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ProposalAssessorGroupMember', through_fields=('proposalassessorgroup', 'emailuser'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='schema',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='taggedproposalapprovergroupactivities',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='taggedproposalapprovergroupregions',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='taggedproposalassessorgroupactivities',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='taggedproposalassessorgroupregions',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
