# Generated by Django 5.2.7 on 2025-12-09 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0298_alter_activitymatrix_schema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='cache_expiry',
            field=models.IntegerField(default=300),
        ),
    ]
