# Generated by Django 5.2.11 on 2026-02-25 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0299_maplayer_cache_expiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaryapprovergroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ApiaryApproverGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiaryassessorgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ApiaryAssessorGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiaryorganisationaccessgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ApiaryOrganisationAccessGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiaryreferralgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ApiaryReferralGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisationaccessgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.OrganisationAccessGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalapprovergroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ProposalApproverGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalassessorgroup',
            name='members',
            field=models.ManyToManyField(through='disturbance.ProposalAssessorGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FileExtensionWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The file extension without the dot, e.g. jpg, pdf, docx, etc', max_length=16)),
                ('model', models.CharField(default='all', max_length=255)),
            ],
            options={
                'unique_together': {('name', 'model')},
            },
        ),
    ]
