# Generated by Django 3.2.25 on 2025-03-28 02:45

import disturbance.components.proposals.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0040_auto_20250327_1703'),
        ('disturbance', '0299_auto_20250113_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualrentalfee',
            name='annual_rental_fee_period',
        ),
        migrations.RemoveField(
            model_name='annualrentalfee',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='annualrentalfee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='annualrentalfeeapiarysite',
            name='annual_rental_fee',
        ),
        migrations.RemoveField(
            model_name='annualrentalfeeapiarysite',
            name='apiary_site',
        ),
        migrations.AlterUniqueTogether(
            name='annualrentalfeeperiod',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ApiaryAnnualRentalFee',
        ),
        migrations.DeleteModel(
            name='ApiaryAnnualRentalFeePeriodStartDate',
        ),
        migrations.DeleteModel(
            name='ApiaryAnnualRentalFeeRunDate',
        ),
        migrations.RemoveField(
            model_name='apiaryapprovergroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='apiaryassessorgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='apiarychecklistanswer',
            name='apiary_referral',
        ),
        migrations.RemoveField(
            model_name='apiarychecklistanswer',
            name='apiary_site',
        ),
        migrations.RemoveField(
            model_name='apiarychecklistanswer',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='apiarychecklistanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='apiarychecklistanswer',
            name='site',
        ),
        migrations.DeleteModel(
            name='ApiaryGlobalSettings',
        ),
        migrations.RemoveField(
            model_name='apiaryorganisationaccessgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='apiaryorganisationaccessgroup',
            name='site',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='assigned_officer',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='referral_group',
        ),
        migrations.RemoveField(
            model_name='apiaryreferralgroup',
            name='district',
        ),
        migrations.RemoveField(
            model_name='apiaryreferralgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='apiaryreferralgroup',
            name='region',
        ),
        migrations.RemoveField(
            model_name='apiarysite',
            name='approval_link_for_vacant',
        ),
        migrations.RemoveField(
            model_name='apiarysite',
            name='latest_approval_link',
        ),
        migrations.RemoveField(
            model_name='apiarysite',
            name='latest_proposal_link',
        ),
        migrations.RemoveField(
            model_name='apiarysite',
            name='proposal_link_for_vacant',
        ),
        migrations.RemoveField(
            model_name='apiarysiteapproval',
            name='apiary_site',
        ),
        migrations.RemoveField(
            model_name='apiarysiteapproval',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='apiarysitefee',
            name='apiary_site_fee_type',
        ),
        migrations.RemoveField(
            model_name='apiarysitefee',
            name='site_category',
        ),
        migrations.RemoveField(
            model_name='apiarysitefeeremainder',
            name='apiary_site_fee_type',
        ),
        migrations.RemoveField(
            model_name='apiarysitefeeremainder',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='apiarysitefeeremainder',
            name='proxy_applicant',
        ),
        migrations.RemoveField(
            model_name='apiarysitefeeremainder',
            name='site_category',
        ),
        migrations.AlterUniqueTogether(
            name='apiarysiteonapproval',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='apiarysiteonapproval',
            name='apiary_site',
        ),
        migrations.RemoveField(
            model_name='apiarysiteonapproval',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='apiarysiteonapproval',
            name='site_category',
        ),
        migrations.AlterUniqueTogether(
            name='apiarysiteonproposal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='apiarysiteonproposal',
            name='apiary_site',
        ),
        migrations.RemoveField(
            model_name='apiarysiteonproposal',
            name='proposal_apiary',
        ),
        migrations.RemoveField(
            model_name='apiarysiteonproposal',
            name='site_category_draft',
        ),
        migrations.RemoveField(
            model_name='apiarysiteonproposal',
            name='site_category_processed',
        ),
        migrations.RemoveField(
            model_name='applicationfee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='applicationfee',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='applicationfeeinvoice',
            name='application_fee',
        ),
        migrations.DeleteModel(
            name='CategoryDbca',
        ),
        migrations.RemoveField(
            model_name='deedpolldocument',
            name='base_proposal',
        ),
        migrations.RemoveField(
            model_name='deedpolldocument',
            name='proposal',
        ),
        migrations.DeleteModel(
            name='DistrictDbca',
        ),
        migrations.DeleteModel(
            name='MigratedApiaryLicence',
        ),
        migrations.RemoveField(
            model_name='onsiteinformation',
            name='apiary_site_on_approval',
        ),
        migrations.RemoveField(
            model_name='proposalapiary',
            name='apiary_sites',
        ),
        migrations.RemoveField(
            model_name='proposalapiary',
            name='originating_approval',
        ),
        migrations.RemoveField(
            model_name='proposalapiary',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalapiary',
            name='target_approval',
        ),
        migrations.RemoveField(
            model_name='proposalapiary',
            name='target_approval_organisation',
        ),
        migrations.RemoveField(
            model_name='proposalapiary',
            name='transferee',
        ),
        migrations.RemoveField(
            model_name='proposalapiarydocument',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalapiarytemporaryuse',
            name='loaning_approval',
        ),
        migrations.RemoveField(
            model_name='proposalapiarytemporaryuse',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='publicliabilityinsurancedocument',
            name='proposal',
        ),
        migrations.DeleteModel(
            name='RegionDbca',
        ),
        migrations.RemoveField(
            model_name='sitetransferapiarysite',
            name='apiary_site_on_approval',
        ),
        migrations.RemoveField(
            model_name='sitetransferapiarysite',
            name='proposal_apiary',
        ),
        migrations.RemoveField(
            model_name='supportingapplicationdocument',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='temporaryuseapiarysite',
            name='apiary_site_on_approval',
        ),
        migrations.RemoveField(
            model_name='temporaryuseapiarysite',
            name='proposal_apiary_temporary_use',
        ),
        migrations.RemoveField(
            model_name='temporaryusepublicliabilityinsurancedocument',
            name='proposal',
        ),
        migrations.DeleteModel(
            name='WaCoast',
        ),
        migrations.AlterModelOptions(
            name='mapcolumn',
            options={'verbose_name': 'map column'},
        ),
        migrations.AlterModelOptions(
            name='maplayer',
            options={'verbose_name': 'map layer'},
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='is_gst_exempt',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='oracle_code_application',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='apiary_approval',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='apiary_sites',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='no_annual_rental_fee_until',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='apiary_compliance',
        ),
        migrations.RemoveField(
            model_name='proposalrequirement',
            name='apiary_approval',
        ),
        migrations.RemoveField(
            model_name='proposalrequirement',
            name='referral_group',
        ),
        migrations.RemoveField(
            model_name='proposalrequirement',
            name='sitetransfer_approval',
        ),
        migrations.AlterField(
            model_name='activitymatrix',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.activitymatrix'),
        ),
        migrations.AlterField(
            model_name='activitymatrix',
            name='schema',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='amendmentrequest',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.amendmentreason'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='domain_used',
            field=models.CharField(choices=[('das', 'DAS'), ('dummy', 'DUMMY')], default='das', max_length=40),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Disturbance Training', 'Disturbance Training'), ('Disturbance Demo', 'Disturbance Demo'), ('Ecological Thinning', 'Ecological Thinning'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Prescribed Burning', 'Prescribed Burning')], max_length=64, verbose_name='Application Type name'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_approvals', to='disturbance.organisation'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='cover_letter_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letter_document', to='disturbance.approvaldocument'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='extracted_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='licence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_document', to='disturbance.approvaldocument'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='proxy_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_proxy_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='renewal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_document', to='disturbance.approvaldocument'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.approval'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='surrender_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='suspension_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assigned_assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliances', to='disturbance.approval'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disturbance_compliance_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disturbance_compliances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complianceamendmentrequest',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.complianceamendmentreason'),
        ),
        migrations.AlterField(
            model_name='comprequest',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportdocument',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.proposal'),
        ),
        migrations.AlterField(
            model_name='exportdocument',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mapcolumn',
            name='map_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='columns', to='disturbance.maplayer'),
        ),
        migrations.AlterField(
            model_name='masterlistquestion',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_request_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='template_group',
            field=models.CharField(choices=[('das', 'DAS'), ('dummy', 'DUMMY')], default='das', max_length=100),
        ),
        migrations.AlterField(
            model_name='organisationrequestdeclineddetails',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='add_info_applicant',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='add_info_assessor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='disturbance.organisation'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='application_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disturbance.applicationtype'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.approval'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='approval_level_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_level_document', to='disturbance.proposaldocument'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='assessor_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='comment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.district'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='gis_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='history_add_info_assessor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='layer_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='previous_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.proposal'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposed_issuance_approval',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proxy_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disturbance_proxy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='refresh_timestamp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.region'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='schema',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='shapefile_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Source/Submitter (multi) polygon geometry'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disturbance_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalapprovergroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.region'),
        ),
        migrations.AlterField(
            model_name='proposalassessorgroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.region'),
        ),
        migrations.AlterField(
            model_name='proposaldeclineddetails',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalrequest',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalrequirement',
            name='standard_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disturbance.proposalstandardrequirement'),
        ),
        migrations.AlterField(
            model_name='proposalstandardrequirement',
            name='system',
            field=models.CharField(choices=[('disturbance', 'Disturbance')], default='disturbance', max_length=20, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Disturbance Training', 'Disturbance Training'), ('Disturbance Demo', 'Disturbance Demo'), ('Ecological Thinning', 'Ecological Thinning'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Prescribed Burning', 'Prescribed Burning')], default='Disturbance', max_length=64, verbose_name='Application name (eg. Disturbance, Ecological Thinning)'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.proposaltype'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='schema',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='proposaltypesection',
            name='proposal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='disturbance.proposaltype'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='label',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='value',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disturbance_referalls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disturbance_assessor_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='parent_question',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='section', chained_model_field='question_sections__section', limit_choices_to={'id__in': set()}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_question', to='disturbance.masterlistquestion'),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sections', to='disturbance.masterlistquestion'),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='disturbance.proposaltypesection'),
        ),
        migrations.AlterField(
            model_name='spatialquerylayer',
            name='assessor_items',
            field=models.JSONField(default=disturbance.components.proposals.models.SpatialQueryLayer.get_default_items, verbose_name='Assessor response set'),
        ),
        migrations.AlterField(
            model_name='spatialquerylayer',
            name='proponent_items',
            field=models.JSONField(default=disturbance.components.proposals.models.SpatialQueryLayer.get_default_items, verbose_name='Proponent response set'),
        ),
        migrations.AlterField(
            model_name='spatialquerymetrics',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='disturbance.proposal'),
        ),
        migrations.AlterField(
            model_name='spatialquerymetrics',
            name='response_cached',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='spatialquerymetrics',
            name='sqs_response',
            field=models.JSONField(default=disturbance.components.proposals.models.SpatialQueryMetrics.get_default_items, verbose_name='Response from SQS'),
        ),
        migrations.AlterField(
            model_name='spatialqueryquestion',
            name='answer_mlq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='disturbance.questionoption'),
        ),
        migrations.AlterField(
            model_name='spatialqueryquestion',
            name='other_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional/Misc Data'),
        ),
        migrations.AlterField(
            model_name='spatialqueryquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='disturbance.masterlistquestion'),
        ),
        migrations.AlterField(
            model_name='taskmonitor',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='application_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenure_app_types', to='disturbance.applicationtype'),
        ),
        migrations.DeleteModel(
            name='AnnualRentalFee',
        ),
        migrations.DeleteModel(
            name='AnnualRentalFeeApiarySite',
        ),
        migrations.DeleteModel(
            name='AnnualRentalFeePeriod',
        ),
        migrations.DeleteModel(
            name='ApiaryApproverGroup',
        ),
        migrations.DeleteModel(
            name='ApiaryAssessorGroup',
        ),
        migrations.DeleteModel(
            name='ApiaryChecklistAnswer',
        ),
        migrations.DeleteModel(
            name='ApiaryChecklistQuestion',
        ),
        migrations.DeleteModel(
            name='ApiaryOrganisationAccessGroup',
        ),
        migrations.DeleteModel(
            name='ApiaryReferral',
        ),
        migrations.DeleteModel(
            name='ApiaryReferralGroup',
        ),
        migrations.DeleteModel(
            name='ApiarySite',
        ),
        migrations.DeleteModel(
            name='ApiarySiteApproval',
        ),
        migrations.DeleteModel(
            name='ApiarySiteFee',
        ),
        migrations.DeleteModel(
            name='ApiarySiteFeeRemainder',
        ),
        migrations.DeleteModel(
            name='ApiarySiteFeeType',
        ),
        migrations.DeleteModel(
            name='ApiarySiteOnApproval',
        ),
        migrations.DeleteModel(
            name='ApiarySiteOnProposal',
        ),
        migrations.DeleteModel(
            name='ApplicationFee',
        ),
        migrations.DeleteModel(
            name='ApplicationFeeInvoice',
        ),
        migrations.DeleteModel(
            name='DeedPollDocument',
        ),
        migrations.DeleteModel(
            name='OnSiteInformation',
        ),
        migrations.DeleteModel(
            name='ProposalApiary',
        ),
        migrations.DeleteModel(
            name='ProposalApiaryDocument',
        ),
        migrations.DeleteModel(
            name='ProposalApiaryTemporaryUse',
        ),
        migrations.DeleteModel(
            name='PublicLiabilityInsuranceDocument',
        ),
        migrations.DeleteModel(
            name='SiteCategory',
        ),
        migrations.DeleteModel(
            name='SiteTransferApiarySite',
        ),
        migrations.DeleteModel(
            name='SupportingApplicationDocument',
        ),
        migrations.DeleteModel(
            name='TemporaryUseApiarySite',
        ),
        migrations.DeleteModel(
            name='TemporaryUsePublicLiabilityInsuranceDocument',
        ),
    ]
