# Generated by Django 5.2.12 on 2026-04-15 03:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0301_alter_apiaryglobalsettings__file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='identification',
            field=models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/apiary/private-media/'), upload_to='organisation/requests/'),
        ),
    ]
