# Generated by Django 5.2.13 on 2026-06-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0302_alter_organisationrequest_identification'),
    ]

    operations = [
        
        migrations.RunSQL(
            sql="ALTER TABLE disturbance_ledgerdocument DROP COLUMN file;",
            reverse_sql="ALTER TABLE disturbance_ledgerdocument ADD COLUMN file varchar(255);"
        ),

    ]
