# Generated by Django 5.2.13 on 2026-06-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0303_remove_ledger_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
