# Generated by Django 5.2.13 on 2026-06-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0304_organisation_property_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
