# Generated by Django 3.2.25 on 2025-03-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20250327_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='billing_same_as_residential',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='postal_same_as_residential',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
